### ISSUE TITLE
Option for verbosity of logs

### ISSUE THREAD

**Issue by jmthackett** [bahuma/oauth2-nextcloud#1]
Hey,

I'm using this module and am getting 405 errors that aren't being logged in any detail to nextcloud's logs. Is there a way to increase the verbosity so I can see the exact problem?

**Comment by bahuma20** [comment]
Hey @jmthackett,

the error handling is usually done by the [oauth2-client](https://github.com/thephpleague/oauth2-client) library, so you can have a look in the documentation there.

You should be able to surround your code with a `catch` block and catch an \League\OAuth2\Client\Provider\Exception\IdentityProviderException. From this you can get the `response` which should contain the body of the http request.

Should look something like this: (untested)
```php
try {
  // Your code
} catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
  // Get the error message:
  $e->getMessage();
  
  // Get the response body:
  $e->getResponseBody();
}
```
