### ISSUE TITLE
Scoped access support for Oauth Tokens

### ISSUE THREAD

**Issue by sunjam** [bahuma/oauth2-nextcloud#2]
As mentioned in your readme and the [official documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/oauth2.html#security-considerations).  Happy to re-file if this is not the proper repo.  Cheers!

> Nextcloud OAuth2 implementation currently does not support scoped access. This means that every token has full access to the complete account including read and write permission to the stored files. It is essential to store the OAuth2 tokens in a safe way!
> 
> Without scopes and restrictable access it is not recommended to use a Nextcloud instance as a user authentication service.

**Comment by bahuma20** [comment]
Hi sunjam, indeed this is the incorrect repo, as it has to be implemented in the Nextcloud Software itself.

So please file this issue against https://github.com/nextcloud/server.

**Comment by sunjam** [comment]
https://github.com/nextcloud/server/issues/26233
