### ISSUE TITLE
Enable Nextcloud Servers without Pretty URLs

### ISSUE THREAD

**Issue by frie** [bahuma/oauth2-nextcloud#3]
When the nextcloud server is not setup for pretty URLs,  2 of the 3 endpoints need to be set up starting the path with index.php. The user info path must not contain index.php, so this cannot be achieved by simply tweaking the base URL.
Easy solution: add a boolean parameter "prettyurl" to the constructor with default false and add index.php when set true. This will let existing code using the client run as before.

**Comment by bahuma20** [comment]
Thank you for reporting! I didn't notice this was an issue.

I did some testing and found out, that you can use the /index.php/ paths also when you have enabled pretty urls. So my solution would be to always add /index.php/ to the authorization and access token urls.

I've done this in the branch `pretty-urls`. 

@frie Can you check out, if this branch is working for you and give me feedback? I don't have an instance without pretty urls here to test.

**Comment by frie** [comment]
Yes, that's the simplest solution and it works. I could not effort a massive test suite, but the interface no works where it did not work before.
